acordio/urls.py
from django.urls import path
from . import views

app_name = "acordio"

urlpatterns = [
    path('', views.index, name='index'),
    path('boot', views.boot, name='boot'),
]

ajax/urls.py
from django.urls import path
from . import views

app_name = "ajax"

urlpatterns = [
    path('', views.index, name='index'),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name='index'),
]

said/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('acordio/', include('acordio.urls')),
    path('sosmed/', include('sosmed.urls')),
    path('ajax/', include('ajax.urls')),
    path('login/', include('login.urls')),
]

sosmed/urls.py
from django.urls import path
from . import views

app_name = "sosmed"

urlpatterns = [
    path('', views.index, name='index'),
]

acordio/models.py
from django.db import models

# Create your models here.

ajax/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

sosmed/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=30, required=False)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

acordio/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'indexAcordio.html')

def boot(request):
    return render(request, 'indexAcordioBoot.html')

ajax/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, "ajax.html")

login/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def index(request):
    return render(request, 'awalan.html')

def login(request):
    if request.method == 'POST': 
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('/login')
        else:
            messages.error(request, 'GAGAL LOGIN')
    return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    messages.success(request, 'Successfully logged out!')
    return redirect('/login')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # print(form)
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            return redirect('/login')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, "index.html")

sosmed/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'sosmed.html')

acordio/templates/indexAcordio.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/acordio.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Story 7{% endblock tittle %}

{% block content %}
<div class="wrapper mr-5 ml-5 mt-5">
      <ul id="acordio" style="list-style: none;">
        <li class="acordio">
          <button class="naik bg-light">^</button>
          <button class="turun bg-light">V</button>
          <button class="accordion mt-5" ><strong>ACTIVITY</strong></button>
          <div class="panel">
            <p>Sekarang lagi sibuk-sibuknya nugas ada story ppw, lab sda, adbis, ppm dll</p>
          </div>
        </li>
        <li class="acordio">
            <button class= "naik bg-light">^</button>
            <button class="turun bg-light">V</button>
            <button class="accordion mt-5" ><strong>EXPERIENCE</strong></button>
            <div class="panel">
              <ul>
                <li>Staff BEM Olahraga Fasilkom UI 2020</li>
                <li>Staff Bisdev PERAK 2020</li>
                <li>Ketua Divisi Danus SBF RUNTIME ERROR 2019</li>
                <li>Staff Acara Sospro MAUNG 2019</li>
                <li>Pengajar Olimpiade Komputer Science Go</li>
              </ul>
            </div>
        </li>
        <li class="acordio">
            <button class= "naik bg-light">^</button>
            <button class="turun bg-light">V</button>
            <button class="accordion mt-5" ><strong>ACHIEVEMENT</strong></button>
            <div class="panel">
              <ul>
                <li>Peserta OSN Komputer 2018</li>
                <li>Medali Emas Olim KOmputer Se-Indonesia OSPO</li>
                <li>Medali Perunggu Olim KOmputer Se-Indonesia USO Unimed</li>
              </ul>
            </div>
        </li>
        <li class="acordio">
            <button class= "naik bg-light">^</button>
            <button class="turun bg-light">V</button>
            <button class="accordion mt-5" ><strong>ABOUT ME</strong></button>
            <div class="panel">
              <p>Hanya seorang mahasiswa perantauan dari Aceh yang menimba ilmu di luar pulau sendiri dan berharap
                akan bermanfaat nantinya
              </p>
            </div>
        </li>
      </ul>
</div>
      
      
      {% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static 'js/acordio.js' %}"></script>
{% endblock js %}

acordio/templates/indexAcordioBoot.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/acordio.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Story 7{% endblock tittle %}

{% block content %}
<div class="wrapper mr-5 ml-5 mt-5">
  <div class="accordion" id="accordionExample" >
      <div class="card rounded mt-5">
        <div class="card-header" id="headingOne" style="background-color: white;">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Collapsible Group Item #1
            </button>
          </h2>
        </div>
    
        <div id="collapseOne" class="collapse bg-light" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
      </div>
      <div class="card rounded mt-5">
        <div class="card-header" id="headingTwo" style="background-color: white;">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Collapsible Group Item #2
            </button>
          </h2>
        </div>
        <div id="collapseTwo" class="collapse bg-light" aria-labelledby="headingTwo" data-parent="#accordionExample">
          <div class="card-body">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
      </div>
      <div class="card rounded mt-5">
        <div class="card-header" id="headingThree" style="background-color: white;">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Collapsible Group Item #3
            </button>
          </h2>
        </div>
        <div id="collapseThree" class="collapse bg-light" aria-labelledby="headingThree" data-parent="#accordionExample">
          <div class="card-body">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
      </div>
      <div class="card rounded mt-5">
        <div class="card-header" id="headingFour" style="background-color: white;">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              Collapsible Group Item #4
            </button>
          </h2>
        </div>
        <div id="collapseFour" class="collapse bg-light" aria-labelledby="headingFour" data-parent="#accordionExample">
          <div class="card-body">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

ajax/templates/ajax.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/ajax.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Story 8{% endblock tittle %}

{% block content %}
<div class="container d-flex justify-content-center mt-5" aria-describedby="button">
  <input type="text" name="q" id="form" class="form"> <button class="btn btn-outline-dark ml-2" id="button">
    <strong>Cari</strong></button>
</div>
<div class="buku ml-5 mr-5 mt-5" id="buku">

</div>
{% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
{% endblock js %}

login/templates/awalan.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/awalan.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Story 9{% endblock tittle %}

{% block content %}
    <div class="pilihan d-flex flex-column justify-content-center">
        {% if user.is_authenticated %}
        <div class="halo  d-flex justify-content-center mb-4 ">
            <strong style="font-size: 64px;"> SELAMAT DATANG {{ user }} </strong>
        </div>
        <div id= "logout" class="logout d-flex justify-content-center mb-4 " style="width: fit-content;">
            <a href= "/login/logout" style="font-size: 64px; background-color: white;" class="p-2 p-2">
                <strong style="color: black;">LOGOUT</strong></a>
        </div>
        {% else %}
        <div class="login d-flex justify-content-center mb-4 " style="width: fit-content;">
            <a href="/login/login" style="font-size: 64px; " class="mr-2 ml-2">
                <strong style="color: black;">LOGIN</strong></a>
        </div>
        <div class="signup d-flex justify-content-center" style="width: fit-content;">
            <a href="/login/signup" style="font-size: 64px;" class="mr-2 ml-2">
                <strong style="color: black;">SIGNUP</strong></a>
        </div>
        {% endif %}
    </div>
{% endblock content %}

login/templates/login.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/awalan.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Story 9{% endblock tittle %}

{% block content %} 
<div class="pilihan">
    <h1 class="title text-center mb-5   "><strong>SELAMAT DATANG DAN LOGIN DISINI YA</strong> <h1>
    <form style="margin-bottom:1%;" action="" method="POST">
        {% csrf_token %}
        <div class="username d-flex">
            <input type="text" name="username" class="mr-3 mb-5"><p>&lt--ISI USERNAME DISINI</p>
        </div>
        <div class="username d-flex">
            <input type="password" name="password" class="mr-3"><p>&lt--ISI PASSWORD DISINI</p>
        </div>
        <button class="submit mt-5" type="submit"><strong>LOGIN</strong></button>
    </form>
</div> 
{% endblock content %}

login/templates/signup.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/awalan.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Story 9{% endblock tittle %}

{% block content %} 
<div class="pilihan">
    <h1 class="title text-center mb-5   "><strong>SELAMAT DATANG DAN SIGNUP DISINI YA</strong> <h1>
        <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
            </p>
        {% endfor %}
        <button class="submit mt-5" type="submit"><strong>SIGNUP</strong></button>
    </form>
</div> 
{% endblock content %}

main/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/landingpage.css' %}" type="text/css">
{% endblock css %}

{% block tittle %}Landing Page{% endblock tittle %}

{% block content %}
<div class="wrapper ml-5 mr-5 mt-5">
    <div class="card mb-3" style="border-radius: 40px;">
        <div class="card-body">
        <a class="card-title" style="font-size: 40px; color: black;"><strong>STORY 7</strong></a>
        <p class="card-text font-italic">Di story ini bakalan ada accordio, dan ada sedikit customisasi sesuai
            dengan yang soal minta :)
        </p>
        <p class="card-text"><small class="text-muted">Moga dapat 100</small></p>
        <button type="button" href="https://getbootstrap.com/docs/4.5/components/buttons/" class="btn btn-light" style="border-radius: 40px;">
            <a href="{% url 'acordio:index' %}">Tekan Ini</a></button>
        <button type="button" href="https://getbootstrap.com/docs/4.5/components/buttons/" class="btn btn-light" style="border-radius: 40px;">
            <a href="{% url 'acordio:boot' %}">Tekan Ini kalo mau yang bootstrap tapi gaada isi</a></button>
        </div>
    </div>    
    <div class="card mb-3" style="border-radius: 40px;">
        <div class="card-body">
        <a class="card-title" style="font-size: 40px; color: black;"><strong>STORY 8</strong></a>
        <p class="card-text font-italic">Di story ini bakalan ada ajax, bakalan minta buku deh pokoknya
        </p>
        <p class="card-text"><small class="text-muted">Moga gatelat kaya story 7</small></p>
        <button type="button" href="https://getbootstrap.com/docs/4.5/components/buttons/" class="btn btn-light" style="border-radius: 40px;">
            <a href="{% url 'ajax:index' %}">Tekan Ini</a></button>
        </div>
    </div>  
    <div class="card mb-3" style="border-radius: 40px;">
        <div class="card-body">
        <a class="card-title" style="font-size: 40px; color: black;"><strong>STORY 9</strong></a>
        <p class="card-text font-italic">Di story ini, bakalan ada laman login-signup-logout 
        </p>
        <p class="card-text"><small class="text-muted">Moga ga error kaya story8</small></p>
        <button type="button" href="https://getbootstrap.com/docs/4.5/components/buttons/" class="btn btn-light" style="border-radius: 40px;">
            <a href="{% url 'login:index' %}">Tekan Ini</a></button>
        </div>
    </div>
</div>
{% endblock content %}

sosmed/templates/sosmed.html
{% extends 'layout.html' %}
{% load static %}

{% block tittle %}Sosmed{% endblock tittle %}

{% block content %}
    <div class="d-flex justify-content-center aligh-items-center mt-5">    
        <h1 style="font-size: 64px;">SORRY GAADA FACEBOOK AMA LINKEDIN..</h1>      
    </div>
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load static %}  

{% block head %}
        
{% endblock head %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- CSS -->
    {% block css %}
        
    {% endblock css %}
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"><!-- FONT -->
    <title>{% block tittle %}{% endblock tittle %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'main:index' %}"><strong>SAID</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active"><a href="https://www.instagram.com/saidnizam.udin/?hl=id">
              <img src="{% static 'image\ig.png' %}" alt=""></a>
            </li>
            <li class="nav-item dropdown"><a href="{% url 'sosmed:index' %}">
              <img src="{% static 'image\facebook.png' %}" alt=""></a>
            </li>
            <li class="nav-item"><a href="{% url 'sosmed:index' %}">
              <img src="{% static 'image\linkedin.png' %}" alt=""></a>
            </li>
          </ul>
        </div>
      </nav>    
        {% block content %}

        {% endblock content %}
        <br><br><br><br><br><br><br><br><br><br><br><br> 
</body>

{% block js %} 

{% endblock js %}
<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>